#!/bin/bash

# Uncomment the line below if you have never configured allegro libraries on this computer before. In subsequent compilations this configuration is unnecessary
#pkg-config --cflags --libs allegro-5 allegro_acodec-5 allegro_audio-5 allegro_color-5 allegro_dialog-5 allegro_font-5 allegro_image-5 allegro_main-5 allegro_memfile-5 allegro_physfs-5 allegro_primitives-5 allegro_ttf-5 allegro_video-5

gcc -o top_gear -W main.c helpers/maps.c helpers/object.c helpers/utils.c helpers/car.c helpers/game.c helpers/menus.c helpers/display.c helpers/colors.c helpers/environment.c helpers/sounds.c helpers/fonts.c -lm -lallegro -lallegro_acodec -lallegro_audio -lallegro_video -lallegro_color -lallegro_dialog -lallegro_image -lallegro_main -lallegro_memfile -lallegro_physfs -lallegro_primitives -lallegro_ttf -lallegro_font -lallegro
